# Generated by Django 5.2.4 on 2025-08-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('task_created', 'Task Created'), ('task_completed', 'Task Completed'), ('project_created', 'Project Created'), ('project_completed', 'Project Completed'), ('points_earned', 'Points Earned'), ('badge_earned', 'Badge Earned'), ('resource_uploaded', 'Resource Uploaded'), ('resource_downloaded', 'Resource Downloaded'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('points_earned', models.PositiveIntegerField(default=0)),
                ('metadata', models.TextField(blank=True, help_text='JSON data for additional context')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
