# Generated by Django 5.2.4 on 2025-08-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='metadata',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Additional context information'),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of related object (task, project, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='related_object_type',
            field=models.CharField(blank=True, help_text='Type of related object', max_length=50),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='session_id',
            field=models.CharField(blank=True, help_text='User session identifier', max_length=50),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='user_agent',
            field=models.TextField(blank=True, help_text="User's browser information"),
        ),
    ]
