# Generated by Django 5.2.4 on 2025-08-18 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('config_type', models.CharField(choices=[('service_account', 'Service Account'), ('oauth', 'OAuth')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('service_account_file', models.FileField(blank=True, null=True, upload_to='google_credentials/')),
                ('client_id', models.CharField(blank=True, max_length=500, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('redirect_uri', models.URLField(blank=True, null=True)),
                ('database_spreadsheet_id', models.CharField(blank=True, max_length=200, null=True)),
                ('drive_folder_id', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Drive Configuration',
                'verbose_name_plural': 'Google Drive Configurations',
            },
        ),
        migrations.CreateModel(
            name='GoogleDriveFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('drive_id', models.CharField(max_length=200, unique=True)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='google_integration.googledrivefolder')),
            ],
            options={
                'verbose_name': 'Google Drive Folder',
                'verbose_name_plural': 'Google Drive Folders',
            },
        ),
        migrations.CreateModel(
            name='GoogleDriveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('drive_id', models.CharField(max_length=200, unique=True)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_type', models.CharField(choices=[('document', 'Document'), ('spreadsheet', 'Spreadsheet'), ('presentation', 'Presentation'), ('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('other', 'Other')], default='other', max_length=20)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('web_view_link', models.URLField(blank=True, null=True)),
                ('web_content_link', models.URLField(blank=True, null=True)),
                ('local_file', models.FileField(blank=True, null=True, upload_to='google_drive_cache/')),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('modified_time', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='pending', max_length=50)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='google_integration.googledrivefolder')),
            ],
            options={
                'verbose_name': 'Google Drive File',
                'verbose_name_plural': 'Google Drive Files',
            },
        ),
        migrations.CreateModel(
            name='GoogleDriveSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('upload', 'Upload'), ('download', 'Download'), ('delete', 'Delete'), ('sync', 'Bidirectional Sync'), ('backup', 'Backup')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('operation_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='google_integration.googledrivefile')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='google_integration.googledrivefolder')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Drive Sync Log',
                'verbose_name_plural': 'Google Drive Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spreadsheet_id', models.CharField(max_length=200)),
                ('sheet_name', models.CharField(max_length=100)),
                ('range_name', models.CharField(default='A:Z', max_length=50)),
                ('django_model', models.CharField(blank=True, max_length=200, null=True)),
                ('column_mapping', models.JSONField(default=dict)),
                ('auto_sync', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=30)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Google Sheets Table',
                'verbose_name_plural': 'Google Sheets Tables',
                'unique_together': {('spreadsheet_id', 'sheet_name')},
            },
        ),
        migrations.CreateModel(
            name='UserGoogleAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Google Authentication',
                'verbose_name_plural': 'User Google Authentications',
            },
        ),
    ]
