# Generated by Django 5.2.4 on 2025-08-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned_to_all',
            field=models.BooleanField(default=False, help_text='If true, this task is visible and submittable by all users'),
        ),
    ]
