# Generated by Django 5.2.4 on 2025-08-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_assigned_to_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='file_path',
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
