# Generated by Django 5.2.4 on 2025-08-20 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_tasksubmission_file_path_tasksubmission_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='allow_member_selection',
            field=models.BooleanField(default=False, help_text='Allow team members to choose this recurring task'),
        ),
        migrations.AddField(
            model_name='task',
            name='instance_date',
            field=models.DateField(blank=True, help_text='The date this recurring task instance is for', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this task repeats'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_template',
            field=models.BooleanField(default=False, help_text='Whether this is a template for recurring tasks'),
        ),
        migrations.AddField(
            model_name='task',
            name='max_assignees',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of team members who can take this recurring task'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_days',
            field=models.CharField(blank=True, help_text="Days of week for weekly tasks (e.g., 'mon,wed,fri')", max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('both', 'Both Daily and Weekly')], help_text='How often this task repeats', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='template_task',
            field=models.ForeignKey(blank=True, help_text='The template task this instance was created from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='tasks.task'),
        ),
        migrations.CreateModel(
            name='TaskRecurringSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('selected_days', models.CharField(blank=True, help_text="Days of week selected (e.g., 'mon,wed,fri')", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_template', models.ForeignKey(help_text='The template task being selected', on_delete=django.db.models.deletion.CASCADE, related_name='member_selections', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_task_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_recurring_selections',
                'ordering': ['-selected_at'],
                'unique_together': {('user', 'task_template', 'selection_type')},
            },
        ),
    ]
