# Generated by Django 5.2.4 on 2025-08-18 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkresourceupload',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_resource_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='googledrivesyncstatus',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_sync_status', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='resourcebulkoperation',
            name='default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.resourcecategory'),
        ),
        migrations.AddField(
            model_name='resource',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='resources.resourcecategory'),
        ),
        migrations.AddField(
            model_name='bulkresourceupload',
            name='default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.resourcecategory'),
        ),
        migrations.AddField(
            model_name='resourcecomment',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='resourcecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcedownload',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
        migrations.AddField(
            model_name='resourcedownload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='downloads',
            field=models.ManyToManyField(related_name='downloaded_resources', through='resources.ResourceDownload', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='resourcefile',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_resource_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcefileaccess',
            name='resource_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='resources.resourcefile'),
        ),
        migrations.AddField(
            model_name='resourcefileaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_file_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcefiledrivesync',
            name='resource_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_sync', to='resources.resourcefile'),
        ),
        migrations.AddField(
            model_name='resourcefileuploadbatch',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_batches', to='resources.resource'),
        ),
        migrations.AddField(
            model_name='resourcefileuploadbatch',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_file_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcefileversion',
            name='resource_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resources.resourcefile'),
        ),
        migrations.AddField(
            model_name='resourcefileversion',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcelike',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource'),
        ),
        migrations.AddField(
            model_name='resourcelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resource',
            name='likes',
            field=models.ManyToManyField(related_name='liked_resources', through='resources.ResourceLike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_material', to='resources.resource'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcedownload',
            unique_together={('resource', 'user')},
        ),
        migrations.AddIndex(
            model_name='resourcefile',
            index=models.Index(fields=['resource', 'file_type'], name='resource_fi_resourc_121c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcefile',
            index=models.Index(fields=['drive_file_id'], name='resource_fi_drive_f_9ed953_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcefile',
            index=models.Index(fields=['is_public'], name='resource_fi_is_publ_aa11ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resourcefileversion',
            unique_together={('resource_file', 'version_number')},
        ),
        migrations.AlterUniqueTogether(
            name='resourcelike',
            unique_together={('resource', 'user')},
        ),
    ]
