# Generated by Django 5.2.4 on 2025-08-18 08:40

from django.db import migrations


def create_default_categories(apps, schema_editor):
    """Create default resource categories"""
    ResourceCategory = apps.get_model('resources', 'ResourceCategory')
    
    default_categories = [
        {
            'name': 'Notes',
            'description': 'Study notes, lecture notes, and personal notes for learning'
        },
        {
            'name': 'Code Files',
            'description': 'Source code files, scripts, and programming examples'
        },
        {
            'name': 'Project Files',
            'description': 'Complete project files, templates, and project resources'
        },
        {
            'name': 'Documents',
            'description': 'PDFs, Word documents, presentations, and other text documents'
        },
        {
            'name': 'Images',
            'description': 'Screenshots, diagrams, charts, and other visual resources'
        },
        {
            'name': 'Videos',
            'description': 'Tutorial videos, recorded lectures, and educational content'
        },
        {
            'name': 'Templates',
            'description': 'Code templates, document templates, and reusable resources'
        },
        {
            'name': 'Tutorials',
            'description': 'Step-by-step guides, how-to documents, and learning materials'
        },
        {
            'name': 'Reference',
            'description': 'Cheat sheets, quick references, and documentation'
        },
        {
            'name': 'Books & Ebooks',
            'description': 'Digital books, ebooks, and reading materials'
        },
        {
            'name': 'Tools & Utilities',
            'description': 'Software tools, utilities, and helpful applications'
        },
        {
            'name': 'Assignments',
            'description': 'Homework assignments, problem sets, and exercises'
        }
    ]
    
    for category_data in default_categories:
        ResourceCategory.objects.get_or_create(
            name=category_data['name'],
            defaults={'description': category_data['description']}
        )


def reverse_default_categories(apps, schema_editor):
    """Remove default categories"""
    ResourceCategory = apps.get_model('resources', 'ResourceCategory')
    
    default_category_names = [
        'Notes', 'Code Files', 'Project Files', 'Documents', 'Images', 
        'Videos', 'Templates', 'Tutorials', 'Reference', 'Books & Ebooks',
        'Tools & Utilities', 'Assignments'
    ]
    
    ResourceCategory.objects.filter(name__in=default_category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_categories, reverse_default_categories),
    ]
